apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- hpa.yaml
commonLabels:
  env: development
patchesStrategicMerge:
- replicas.yaml
- limits.yaml
- affinity.yaml