apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-poc
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine-type
                operator: In
                values:
                - small
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-poc
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100