apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- hpa.yaml
commonLabels:
  env: production
patchesStrategicMerge:
- replicas.yaml
- limits.yaml