apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-poc
spec:
  template:
    spec:
      containers:
      - name: app-poc
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"