apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: app-poc
resources:
- deployment.yaml
- pdb.yaml
- service.yaml
patchesStrategicMerge:
- strategy.yaml
- security.yaml
- probes.yaml
