apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-poc
spec:
  template:
    spec:
      containers:
      - name: app-poc
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 1