apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-poc 
  name: app-poc-svc
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: app-poc
  sessionAffinity: None
  type: ClusterIP
