apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-poc-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-poc
  targetCPUUtilizationPercentage: 65